# default
mymap:
  api:
    version: "${version}"

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/D:/h2/mymap
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: com.sillimfive.mymap.config.CustomNamingStrategy
      ddl-auto: create
    open-in-view: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/mymap_dev
    username: mymap
    password: mymap123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  com.sillimfive.mymap: info

---

spring:
  config:
    activate:
      on-profile: swagger

springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  #    path: /mymap-api.html
  api-docs:
    enabled: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/mymap
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: info