spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/D:/h2/mymap
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.sillimfive.mymap.config.CustomNamingStrategy
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/mymap
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.sillimfive.mymap.config.CustomNamingStrategy
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

